-- NOTE: USE ONLY WHEN NEEDED
USE HCManagementSystem;
GO

DROP TABLE IF EXISTS Complaint;
DROP TABLE IF EXISTS Feedback;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS CustOrder;
DROP TABLE IF EXISTS MenuItemCuisine;
DROP TABLE IF EXISTS MenuItem;
DROP TABLE IF EXISTS Cuisine;
DROP TABLE IF EXISTS RentalAgreement;
DROP TABLE IF EXISTS Promotion;
DROP TABLE IF EXISTS InspectionRemark;
DROP TABLE IF EXISTS Inspection;
DROP TABLE IF EXISTS FoodStall;
DROP TABLE IF EXISTS HawkerCentre;

DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS StallOwner;
DROP TABLE IF EXISTS NEA_Officer;
DROP TABLE IF EXISTS Operator;
GO
